server:
  port: 8080
spring:
  application:
    name: IA-RAG
  resources:
    static-locations: "classpath:/public/"
  jmx:
    enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/rag
    port: 3306
    username: root
    password: 49454945
  ai:
    vectorstore:
      mariadb:
        initialize-schema: true
        distance-type: COSINE
    ollama:
      init:
        pull-model-strategy=always: true
      base-url: http://localhost:11434
      embedding:
        options:
          model: mistral-nemo:12b-instruct-2407-q8_0
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,hawtio, jolokia'
hawtio:
  authenticationEnabled: false

aquila:
  rag:
    location: /RAG/

---
spring:
  config:
    activate:
      on-profile: gros
  ai:
    ollama:
      chat:
        options:
          model: 'mistral-nemo:12b-instruct-2407-q8_0'
          temperature: 0.7
---
spring:
  config:
    activate:
      on-profile: rog
  ai:
    ollama:
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.7
