server:
  port: 9090
spring:
  application:
    name: IA-RAG
  jmx:
    enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/vector
    port: 3306
    username: root
    password: 49454945
  ai:
    vectorstore:
      mariadb:
        initialize-schema: true
        distance-type: COSINE
        dimensions: 1536
    ollama:
      init:
        pull-model-strategy=always:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.7

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,hawtio, jolokia'
hawtio:
  authenticationEnabled: false