server:
  port: 8080
spring:
  application:
    name: IA-RAG
  resources:
    static-locations: "classpath:/public/"
  jmx:
    enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/rag
    username: root
    password: 49454945
  ai:
    vectorstore:
      mariadb:
        initialize-schema: true
        distance-type: COSINE
    ollama:
      init:
        pull-model-strategy: WHEN_MISSING
      base-url: http://localhost:11434
      embedding:
        options:
          model: deepseek-r1:7b
          temperature: 0.4

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,hawtio, jolokia'
hawtio:
  authenticationEnabled: false

aquila:
  rag:
    location: /RAG_SMALL/

---
spring:
  config:
    activate:
      on-profile: test
  ai:
    ollama:
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.7
---
spring:
  config:
    activate:
      on-profile: gros
  ai:
    ollama:
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.7
---
spring:
  config:
    activate:
      on-profile: rog
  ai:
    ollama:
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.7
